# Generated by Django 5.2.8 on 2026-01-31 12:40

import car_insurance.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_insurance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInsuranceQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True)),
                ('coverage_type', models.CharField(choices=[('third_party', 'Third Party Only'), ('third_party_fire_theft', 'Third Party Fire & Theft'), ('comprehensive', 'Comprehensive')], default='comprehensive', max_length=25)),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('excess_amount', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=8)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('claims_history', models.IntegerField(default=0, help_text='Number of previous claims')),
                ('no_claims_years', models.IntegerField(default=0, help_text='Years of no claims bonus')),
                ('base_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('final_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_insurance_quote',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(default=car_insurance.models.generate_policy_number, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('document_url', models.FileField(blank=True, null=True, upload_to='policy_documents/')),
                ('inception_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('total_premium', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='car_insurance.carinsurancequote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Car policies',
                'db_table': 'car_insurance_policy',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=20, unique=True)),
                ('claim_date', models.DateField(auto_now_add=True)),
                ('incident_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(default='No description provided')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid')], default='submitted', max_length=20)),
                ('incident_type', models.CharField(default='Accident', max_length=100)),
                ('third_party_involved', models.BooleanField(default=False)),
                ('police_report', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_insurance.carpolicy')),
            ],
            options={
                'db_table': 'car_insurance_claim',
                'ordering': ['-claim_date'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='Toyota', max_length=50)),
                ('model', models.CharField(default='Camry', max_length=50)),
                ('year', models.IntegerField(default=2020)),
                ('license_plate', models.CharField(max_length=20, unique=True, verbose_name='License Plate')),
                ('vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='Vehicle Identification Number')),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('motorcycle', 'Motorcycle'), ('truck', 'Truck'), ('suv', 'SUV')], default='car', max_length=20)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20)),
                ('engine_size', models.DecimalField(decimal_places=1, default=Decimal('1.6'), help_text='Engine size in liters', max_digits=3)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_commercial', models.BooleanField(default=False)),
                ('annual_mileage', models.IntegerField(default=10000, help_text='Annual mileage in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'car_insurance_vehicle',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='carpolicy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_insurance.vehicle'),
        ),
        migrations.AddField(
            model_name='carinsurancequote',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_insurance.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Vehicle Registration'), ('insurance', 'Insurance Certificate'), ('inspection', 'Inspection Report'), ('accident', 'Accident Report'), ('other', 'Other')], default='other', max_length=20)),
                ('document_file', models.FileField(upload_to='vehicle_documents/')),
                ('description', models.CharField(blank=True, default='No description', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_insurance.vehicle')),
            ],
            options={
                'db_table': 'car_insurance_vehicledocument',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
