# Generated by Django 5.2.8 on 2026-01-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'ملف شخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار الرخصة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='driving_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم رخصة القيادة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sensitive_info_locked',
            field=models.BooleanField(default=False, verbose_name='المعلومات الحساسة مقفلة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
